import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter, Roboto, Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '../../context/ThemeContext';
import {SessionProvider} from 'next-auth/react'
import AuthProvider from '@/components/AuthProvider/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sai next app',
  description: 'Generated by  sai create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
         {/* <SessionProvider> */}
         <AuthProvider>
         <div className='container'>
            {/* <h3>This main layout page</h3> */}
            <Navbar />
            {children}
            <Footer />
          </div>
         </AuthProvider>
        
         {/* </SessionProvider> */}
        </ThemeProvider>


      </body>
    </html>
  )
}
